theme = "Catppuccin-frappe"
client_id_command = "echo $SPOTIFY_PLAYER_CLIENT_ID"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
track_table_item_max_len = 32
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
playback_window_position = "Bottom"
progress_bar_type = "Rectangle"
progress_bar_position = "Right"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
playback_window_width = 6
enable_media_control = false
enable_streaming = true
enable_cover_image_cache = true
default_device = "spotify-player"

[copy_command]
command = "pbcopy"
args = []

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 160
audio_cache = false
