[cache]
dir = "~/Library/Caches/tlrc"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
line_length = 0
compact = false
option_style = "both"
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
color = { hex = "#ca9ee6" }
background = "default"
bold = true
underline = false
italic = true
dim = false
strikethrough = false

[style.description]
color = { hex = "#f2d5cf" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color = { hex = "#c6d0f5" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
color = { hex = "#8caaee" }
background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.url]
color = { hex = "#ef9f76" }
background = "default"
bold = true
underline = true
italic = false
dim = false
strikethrough = false

[style.inline_code]
color = { hex = "#a6d189" }
background = "default"
bold = true
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
color = { hex = "#f4b8e4" }
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false
