# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  timeFormat: Jan 2 06
  theme:
    activeBorderColor:
      - "#ca9ee6"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ca9ee6"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "winnie": "#f4b8e4"
    "dependabot[bot]": "#8caaee"
    "*": "#babbf1"
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: 'delta --paging=never --features=catppuccin-frappe --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
  parseEmoji: true
  overrideGpg: true
os:
  editPreset: "nvim-remote"
keybinding:
  universal:
    createPatchOptionsMenu: <c-x>
    scrollUpMain-alt1: <c-p>
    scrollDownMain-alt1: <c-n>
    gotoTop-alt: g
    gotoBottom-alt: G
