# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  timeFormat: Jan 2 06
  theme:
    activeBorderColor:
      - "#ca9ee6"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ca9ee6"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "winnie": "#f4b8e4"
    "dependabot[bot]": "#8caaee"
    "*": "#babbf1"
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: 'delta --paging=never --features=catppuccin-frappe --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
  parseEmoji: true
  overrideGpg: true
os:
  editPreset: "nvim-remote"
keybinding:
  universal:
    createPatchOptionsMenu: <c-x>
    scrollUpMain-alt1: <c-p>
    scrollDownMain-alt1: <c-n>
    gotoTop-alt: g
    gotoBottom-alt: G
customCommands:
  - key: "C"
    command: "meteor"
    description: "Commit with meteor"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: "t"
    context: "files"
    description: "Interactive conventional commit"
    prompts:
      - type: "menu"
        title: "Type of change"
        key: "Type"
        options:
          - name: "âœ¨ feat"
            value: "feat"
          - name: "ğŸ› fix"
            value: "fix"
          - name: "ğŸ“š docs"
            value: "docs"
          - name: "ğŸ¨ style"
            value: "style"
          - name: "â™»ï¸  refactor"
            value: "refactor"
          - name: "âš¡ perf"
            value: "perf"
          - name: "ğŸš¨ test"
            value: "test"
          - name: "ğŸ“¦ build"
            value: "build"
          - name: "ğŸ‘· ci"
            value: "ci"
          - name: "ğŸ”§ chore"
            value: "chore"
          - name: "ğŸ—‘ï¸  revert"
            value: "revert"
      - type: "input"
        title: "Scope (optional):"
        key: "Scope"
        initialValue: ""
      - type: "menu"
        title: "Breaking change?"
        key: "Breaking"
        options:
          - name: "no"
            value: "no"
            key: "n"
          - name: "yes"
            value: "yes"
            key: "y"
      - type: "input"
        title: "Message:"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit this?"
        key: "Confirm"
        body: |
          {{.Form.Type}}{{ if .Form.Scope }}({{.Form.Scope}}){{ end }}{{ if eq .Form.Breaking "yes" }}!{{ end }}: {{ if eq .Form.Type "feat" }}âœ¨{{ else if eq .Form.Type "fix" }}ğŸ›{{ else if eq .Form.Type "docs" }}ğŸ“š{{ else if eq .Form.Type "style" }}ğŸ¨{{ else if eq .Form.Type "refactor" }}â™»ï¸{{ else if eq .Form.Type "perf" }}âš¡{{ else if eq .Form.Type "test" }}ğŸš¨{{ else if eq .Form.Type "build" }}ğŸ“¦{{ else if eq .Form.Type "ci" }}ğŸ‘·{{ else if eq .Form.Type "chore" }}ğŸ”§{{ else if eq .Form.Type "revert" }}ğŸ—‘ï¸{{ end }} {{.Form.Message}}
    command: >-
      git commit --message '{{.Form.Type}}{{ if .Form.Scope }}({{.Form.Scope}}){{ end }}{{ if eq .Form.Breaking "yes" }}!{{ end }}: {{ if eq .Form.Type "feat" }}âœ¨{{ else if eq .Form.Type "fix" }}ğŸ›{{ else if eq .Form.Type "docs" }}ğŸ“š{{ else if eq .Form.Type "style" }}ğŸ¨{{ else if eq .Form.Type "refactor" }}â™»ï¸{{ else if eq .Form.Type "perf" }}âš¡{{ else if eq .Form.Type "test" }}ğŸš¨{{ else if eq .Form.Type "build" }}ğŸ“¦{{ else if eq .Form.Type "ci" }}ğŸ‘·{{ else if eq .Form.Type "chore" }}ğŸ”§{{ else if eq .Form.Type "revert" }}ğŸ—‘ï¸{{ end }} {{.Form.Message}}'
