# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  timeFormat: Jan 2 06
  theme:
    activeBorderColor:
      - "#ca9ee6"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ca9ee6"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "winnie": "#f4b8e4"
    "dependabot[bot]": "#8caaee"
    "*": "#babbf1"
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: 'delta --paging=never --features=catppuccin-frappe --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
  parseEmoji: true
os:
  editPreset: "nvim-remote"
keybinding:
  universal:
    scrollUpMain-alt1: <c-k>
    scrollDownMain-alt1: <c-j>
    gotoTop-alt: g
    gotoBottom-alt: G
# Git-Town
# customCommands:
#   - key: "Y"
#     context: "global"
#     description: "Git-Town sYnc"
#     command: "git-town sync --all"
#     loadingText: "Syncing"
#     output: log
#   - key: "U"
#     context: "global"
#     description: "Git-Town Undo (undo the last git-town command)"
#     command: "git-town undo"
#     prompts:
#       - type: "confirm"
#         title: "Undo Last Command"
#         body: "Are you sure you want to Undo the last git-town command?"
#     loadingText: "Undoing Git-Town Command"
#     output: log
#   - key: "!"
#     context: "global"
#     description: "Git-Town Repo (opens the repo link)"
#     command: "git-town repo"
#     loadingText: "Opening Repo Link"
#     output: log
#   - key: "a"
#     context: "localBranches"
#     description: "Git-Town Append"
#     prompts:
#       - type: "input"
#         title: "Enter name of new child branch. Branches off of '{{.CheckedOutBranch.Name}}'"
#         key: "BranchName"
#     command: "git-town append {{.Form.BranchName}}"
#     loadingText: "Appending"
#     output: log
#   - key: "H"
#     context: "localBranches"
#     description: "Git-Town Hack (creates a new branch)"
#     prompts:
#       - type: "input"
#         title: "Enter name of new branch. Branches off of 'Main'"
#         key: "BranchName"
#     command: "git-town hack {{.Form.BranchName}}"
#     loadingText: "Hacking"
#     output: log
#   - key: "K"
#     context: "localBranches"
#     description: "Git-Town Kill (deletes the current feature branch and sYnc)"
#     command: "git-town kill"
#     prompts:
#       - type: "confirm"
#         title: "Delete current feature branch"
#         body: "Are you sure you want to delete the current feature branch?"
#     loadingText: "Killing Feature Branch"
#     output: log
#   - key: "p"
#     context: "localBranches"
#     description: "Git-Town Propose (creates a pull request)"
#     command: "git-town propose"
#     loadingText: "Creating pull request"
#     output: log
#   - key: "P"
#     context: "localBranches"
#     description: "Git-Town Prepend (creates a branch between the curent branch and its parent)"
#     prompts:
#       - type: "input"
#         title: "Enter name of the for child branch between '{{.CheckedOutBranch.Name}}' and its parent"
#         key: "BranchName"
#     command: "git-town prepend {{.Form.BranchName}}"
#     loadingText: "Prepending"
#     output: log
#   - key: "S"
#     context: "localBranches"
#     description: "Git-Town Skip (skip branch with merge conflicts when syncing)"
#     command: "git-town skip"
#     loadingText: "Skiping"
#     output: log
#   - key: "G"
#     context: "files"
#     description: "Git-Town GO aka:continue (continue after resolving merge conflicts)"
#     command: "git-town continue"
#     loadingText: "Continuing"
#     output: log
