# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - builtin: pageDown
      key: "ctrl+n"
    - builtin: pageUp
      key: "ctrl+p"
    - key: g
      name: lazygit
      command: |
        cd {{.RepoPath}}; lazygit
    - key: f
      name: forgit log
      command: |
        cd {{.RepoPath}}; git forgit log
  prs:
    - key: v
      name: approve
      command: |
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}
  issues:
    - builtin: unassign
      key: u
    - key: a
      name: assign @me
      command: |
        gh issue edit {{.IssueNumber}} --add-assignee @me
    - key: A
      name: assign @copilot
      command: |
        gh issue edit {{.IssueNumber}} --add-assignee @copilot
    - key: n
      name: create new issue
      command: |
        gh issue create
    - key: e
      name: create dev branch
      command: |
        gh issue develop {{.IssueNumber}} --repo {{.RepoName}}
repoPaths:
  gwenwindflower/*: ~/dev/*
  gwenwindflower/.charmschool: ~/.charmschool
  gwenwindflower/dotfiles: ~/.local/share/chezmoi
theme:
  colors:
    text:
      primary: "#c6d0f5"
      secondary: "#f4b8e4"
      inverted: "#232634"
      faint: "#b5bfe2"
      warning: "#e5c890"
      success: "#a6d189"
      error: "#e78284"
    background:
      selected: "#414559"
    border:
      primary: "#f4b8e4"
      secondary: "#51576d"
      faint: "#414559"
  ui:
    table:
      showSeparator: true
pager:
  diff: delta
