"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = ["<C-p>"]
run = "seek -5"
desc = "Seek up 5 units in the preview"

[[mgr.prepend_keymap]]
on = ["<C-n>"]
run = "seek 5"
desc = "Seek down 5 units in the preview"

[[mgr.prepend_keymap]]
on = ["<C-[>"]
run = "back"
desc = "Navigate back in history"

[[mgr.prepend_keymap]]
on = ["<C-]>"]
run = "forward"
desc = "Navigate forward in history"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to current git repository root"

[[mgr.prepend_keymap]]
on = ["'", ";"]
run = "plugin custom-shell -- auto --interactive"
desc = "custom-shell as default, interactive"

[[mgr.prepend_keymap]]
on = ["'", ":"]
run = "plugin custom-shell -- auto --interactive --block"
desc = "custom-shell as default, interactive, block"

[[mgr.prepend_keymap]]
on = ["'", "h"]
run = "plugin custom-shell history"
desc = "Show Custom-shell history"

[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = "@"
run = "plugin bunny"

[[mgr.prepend_keymap]]
desc = "Start bunny.yazi fuzzy search"
on = ["g", "@"]
run = "plugin bunny fuzzy"
